spring:
  datasource:
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/questionnaire_portal

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreplyquestionnaireapp@gmail.com
    password: szinzpuudliibyyu
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  data:
    web:
      pageable:
        default-page-size: 4
        one-indexed-parameters: true
app:
  jwt:
    secret: 26452948404D6351665468576D5A7134743777217A25432A462D4A614E645267
    live-time: 720000000
    issuer: Questionnaires App
  server.url: http://localhost:8080